-- MySQL Script generated by MySQL Workbench
-- Mon Jun  8 00:20:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PESSOAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PESSOAS` (
  `idpessoa` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idTelefone` INT NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `pessoaID` INT NOT NULL,
  PRIMARY KEY (`idTelefone`, `pessoaID`),
  INDEX `fk_Telefone_PESSOAS_idx` (`pessoaID` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_PESSOAS`
    FOREIGN KEY (`pessoaID`)
    REFERENCES `mydb`.`PESSOAS` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos` (
  `idAlunos` INT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `pessoaID` INT NOT NULL,
  PRIMARY KEY (`idAlunos`, `pessoaID`),
  INDEX `fk_Alunos_PESSOAS1_idx` (`pessoaID` ASC) VISIBLE,
  UNIQUE INDEX `pessoaID_UNIQUE` (`pessoaID` ASC) VISIBLE,
  CONSTRAINT `fk_Alunos_PESSOAS1`
    FOREIGN KEY (`pessoaID`)
    REFERENCES `mydb`.`PESSOAS` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planos` (
  `idPlanos` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `duração_meses` INT NOT NULL,
  PRIMARY KEY (`idPlanos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matrículas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matrículas` (
  `idMatrículas` INT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `data_início` DATE NOT NULL,
  `data_fim` DATE NULL,
  `alunosID` INT NOT NULL,
  `planoID` INT NOT NULL,
  PRIMARY KEY (`idMatrículas`, `alunosID`, `planoID`),
  INDEX `fk_Matrículas_Alunos1_idx` (`alunosID` ASC) VISIBLE,
  INDEX `fk_Matrículas_Planos1_idx` (`planoID` ASC) VISIBLE,
  CONSTRAINT `fk_Matrículas_Alunos1`
    FOREIGN KEY (`alunosID`)
    REFERENCES `mydb`.`Alunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matrículas_Planos1`
    FOREIGN KEY (`planoID`)
    REFERENCES `mydb`.`Planos` (`idPlanos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamentos` (
  `idPagamentos` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `vencimento` DATE NOT NULL,
  `data_pagamento` DATE NULL,
  `status` VARCHAR(20) NOT NULL,
  `matriculaID` INT NOT NULL,
  PRIMARY KEY (`idPagamentos`, `matriculaID`),
  INDEX `fk_Pagamentos_Matrículas1_idx` (`matriculaID` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamentos_Matrículas1`
    FOREIGN KEY (`matriculaID`)
    REFERENCES `mydb`.`Matrículas` (`idMatrículas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsabilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsabilidades` (
  `idResponsabilidades` INT NOT NULL,
  `responsavelD` INT NOT NULL,
  `alunoID` INT NOT NULL,
  `tipo_responsabilidade` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idResponsabilidades`, `responsavelD`, `alunoID`),
  INDEX `fk_Responsabilidades_PESSOAS1_idx` (`responsavelD` ASC) VISIBLE,
  INDEX `fk_Responsabilidades_Alunos1_idx` (`alunoID` ASC) VISIBLE,
  CONSTRAINT `fk_Responsabilidades_PESSOAS1`
    FOREIGN KEY (`responsavelD`)
    REFERENCES `mydb`.`PESSOAS` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsabilidades_Alunos1`
    FOREIGN KEY (`alunoID`)
    REFERENCES `mydb`.`Alunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modalidades` (
  `idModalidades` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descriçao` TEXT(300) NULL,
  PRIMARY KEY (`idModalidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CTs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CTs` (
  `idCTs` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCTs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horários`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horários` (
  `idHorários` INT NOT NULL,
  `modalidadeID` INT NOT NULL,
  `ctID` INT NOT NULL,
  `dia_semana` VARCHAR(45) NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `descrição` TEXT(300) NULL,
  PRIMARY KEY (`idHorários`, `modalidadeID`, `ctID`),
  INDEX `fk_Horários_Modalidades1_idx` (`modalidadeID` ASC) VISIBLE,
  INDEX `fk_Horários_CTs1_idx` (`ctID` ASC) VISIBLE,
  CONSTRAINT `fk_Horários_Modalidades1`
    FOREIGN KEY (`modalidadeID`)
    REFERENCES `mydb`.`Modalidades` (`idModalidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horários_CTs1`
    FOREIGN KEY (`ctID`)
    REFERENCES `mydb`.`CTs` (`idCTs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Presenças`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Presenças` (
  `idPresenças` INT NOT NULL,
  `alunoID` INT NOT NULL,
  `data_presença` DATE NOT NULL,
  `horarioID` INT NOT NULL,
  PRIMARY KEY (`idPresenças`, `alunoID`, `horarioID`),
  INDEX `fk_Presenças_Alunos1_idx` (`alunoID` ASC) VISIBLE,
  INDEX `fk_Presenças_Horários1_idx` (`horarioID` ASC) VISIBLE,
  CONSTRAINT `fk_Presenças_Alunos1`
    FOREIGN KEY (`alunoID`)
    REFERENCES `mydb`.`Alunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Presenças_Horários1`
    FOREIGN KEY (`horarioID`)
    REFERENCES `mydb`.`Horários` (`idHorários`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereços`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereços` (
  `idEndereços` INT NOT NULL,
  `ctID` INT NOT NULL,
  `rua` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idEndereços`, `ctID`),
  INDEX `fk_Endereços_CTs1_idx` (`ctID` ASC) VISIBLE,
  CONSTRAINT `fk_Endereços_CTs1`
    FOREIGN KEY (`ctID`)
    REFERENCES `mydb`.`CTs` (`idCTs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
